#!/bin/bash
# Causes the device to run in wifi client mode

python3 /usr/lib/pi-wifi-dash/scripts/reset/reset.py &

python3 /usr/lib/pi-wifi-dash/scripts/reset/check_wifi_active.py &

python3 /usr/lib/pi-wifi-dash/webserver/app.py &

dhclient -r
# dhclient renewal to get the router's gateway IP address